# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

reviewers:
  - nicodeur

assignees:
  - nicodeur

numberOfAssignees: 1
